In [1]:
import pandas as pd 

import numpy as np

## EmploymentExperience
- EmployeeID (FK)
- YearsAtCompany
- YearsSinceLastPromotion
- YearsInCurrentRole
- YearsWithCurrentManager

## CompanyStandards
- Salary 
- AverageSalary // Propuesta de nueva columna para hacer la media de ingresos de los empleados
- StandardHours

In [2]:
data = pd.read_csv("../files/HR_RAW_DATA.csv")


In [3]:
data.columns

Index(['Unnamed: 0', 'Age', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'employeecount', 'employeenumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NUMCOMPANIESWORKED', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TOTALWORKINGYEARS', 'TrainingTimesLastYear',
       'WORKLIFEBALANCE', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YEARSWITHCURRMANAGER',
       'SameAsMonthlyIncome', 'DateBirth', 'Salary', 'RoleDepartament',
       'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [4]:
data.head(2)

Unnamed: 0 Age Attrition BusinessTravel DailyRate Department  \
0           0  51        No            NaN    684,0$        NaN   
1           1  52        No            NaN    699,0$        NaN   

   DistanceFromHome  Education EducationField  employeecount  ...  \
0                 6          3            NaN              1  ...   
1                 1          4  Life Sciences              1  ...   

  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0             20                 NaN                       15   
1             33                 NaN                       11   

  YEARSWITHCURRMANAGER  SameAsMonthlyIncome  DateBirth       Salary  \
0                   15              19537,0       1972  1000000000$   
1                    9              19999,0       1971  1000000000$   

   RoleDepartament NUMBERCHILDREN RemoteWork  
0              NaN            NaN        Yes  
1              NaN            NaN          1  

[2 rows x 42 columns]

In [5]:
employee_experience= data.loc[: , ['employeenumber', 'YearsAtCompany','YearsInCurrentRole', 'YearsSinceLastPromotion','YEARSWITHCURRMANAGER']]

In [6]:
employee_experience.head()

employeenumber  YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0          162,0              20                NaN                       15   
1          259,0              33                NaN                       11   
2          319,0              22                NaN                       11   
3            NaN              20                NaN                        5   
4            NaN              19                NaN                        2   

   YEARSWITHCURRMANAGER  
0                    15  
1                     9  
2                    15  
3                     6  
4                     8

In [8]:
# PORCENTAJES DE NULOS EN LA TABLA  E-E 

employee_experience.isna().sum()/employee_experience.shape[0]*100

employeenumber             26.703841
YearsAtCompany              0.000000
YearsInCurrentRole         97.893432
YearsSinceLastPromotion     0.000000
YEARSWITHCURRMANAGER        0.000000
dtype: float64

In [12]:
employee_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1614 entries, 0 to 1613
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   employeenumber           1183 non-null   object
 1   YearsAtCompany           1614 non-null   int64 
 2   YearsInCurrentRole       34 non-null     object
 3   YearsSinceLastPromotion  1614 non-null   int64 
 4   YEARSWITHCURRMANAGER     1614 non-null   int64 
dtypes: int64(3), object(2)
memory usage: 63.2+ KB


In [9]:

employee_experience["YearsInCurrentRole"] = employee_experience["YearsInCurrentRole"].str.replace(",", ".")

In [13]:
employee_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1614 entries, 0 to 1613
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   employeenumber           1183 non-null   object
 1   YearsAtCompany           1614 non-null   int64 
 2   YearsInCurrentRole       34 non-null     object
 3   YearsSinceLastPromotion  1614 non-null   int64 
 4   YEARSWITHCURRMANAGER     1614 non-null   int64 
dtypes: int64(3), object(2)
memory usage: 63.2+ KB


In [99]:
employee_experience['YearsInRole'] = employee_experience['YearsInCurrentRole'].fillna(0).replace(',', '.', regex=True).astype(int)

In [101]:
employee_experience

employeenumber  YearsAtCompany YearsInCurrentRole  \
0             162,0              20                nan   
1             259,0              33                nan   
2             319,0              22                nan   
3               NaN              20                nan   
4               NaN              19                nan   
...             ...             ...                ...   
1609          967,0              16                nan   
1610          972,0               9                nan   
1611            NaN               8                nan   
1612          990,0               7                nan   
1613            NaN               8                nan   

      YearsSinceLastPromotion  YEARSWITHCURRMANAGER  
0                          15                    15  
1                          11                     9  
2                          11                    15  
3                           5                     6  
4                           2                     8  
...                       ...                   ...  
1609                        3                     7  
1610                        0                     8  
1611                        0                     7  
1612                        0                     7  
1613                        0                     7  

[1614 rows x 5 columns]

# Employee number

In [ ]:
#numero de nulo en la columna de employee number
data.employeenumber.isnull().sum()

431

In [ ]:
#numero de duplicados en la columna de employee number 
data.employeenumber.duplicated().sum()

534

# Years at company

In [ ]:
##numero de nulo en la columna years at company
data.YearsAtCompany.isnull().sum()

0

In [ ]:
data.YearsAtCompany.duplicated().sum()

1577

In [ ]:
data.YearsAtCompany.unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

In [ ]:
data.YearsAtCompany.value_counts()

5     208
1     171
3     141
2     141
10    133
7     115
4     114
8     106
9      94
6      78
0      44
11     36
20     29
13     26
15     21
14     19
22     17
12     15
18     15
16     14
21     14
19     12
17      9
24      7
25      5
33      5
26      4
32      3
27      3
31      3
36      3
29      2
23      2
40      2
34      1
37      1
30      1
Name: YearsAtCompany, dtype: int64

#  Years since last promotion

In [ ]:
data.YearsSinceLastPromotion.isnull().sum()

0

In [ ]:
data.YearsSinceLastPromotion.duplicated().sum()

1598

In [ ]:
data.duplicated(subset= "YearsSinceLastPromotion").sum()

1598

In [ ]:
data.YearsSinceLastPromotion.unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

In [ ]:
data.YearsSinceLastPromotion.value_counts()

0     625
1     384
2     177
7      93
4      67
3      62
5      53
6      37
11     26
8      20
9      18
15     15
12     11
13     10
14     10
10      6
Name: YearsSinceLastPromotion, dtype: int64

# Years in current role

In [ ]:
data.YearsInCurrentRole.isnull().sum()

1580

In [ ]:
data.YearsInCurrentRole.duplicated().sum()

1603

In [ ]:
# los valores encontrados estan como string paasar a float 

data.YearsInCurrentRole.unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [ ]:
data.YearsInCurrentRole.value_counts()

2,0     11
7,0      5
0,0      4
4,0      3
1,0      3
11,0     2
6,0      2
3,0      2
13,0     1
12,0     1
Name: YearsInCurrentRole, dtype: int64

In [ ]:
data.YearsInCurrentRole

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611    NaN
1612    NaN
1613    NaN
Name: YearsInCurrentRole, Length: 1614, dtype: object

In [ ]:


for dato, value in enumerate(employee_experience["YearsInCurrentRole"]):
    try:
        employee_experience.at[dato, "YearsInCurrentRole"] = int(value)
    except (ValueError, TypeError):
        # Si ocurre un error (por ejemplo, si el valor es una cadena no numérica o NaN),
        # cambia el valor a un entero
        employee_experience.at[dato, "YearsInCurrentRole"] = 0  # Puedes cambiar esto por cualquier otro valor entero

# Muestra el DataFrame actualizado
employee_experience


employeenumber  YearsAtCompany YearsInCurrentRole  \
0             162,0              20                  0   
1             259,0              33                  0   
2             319,0              22                  0   
3               NaN              20                  0   
4               NaN              19                  0   
...             ...             ...                ...   
1609          967,0              16                  0   
1610          972,0               9                  0   
1611            NaN               8                  0   
1612          990,0               7                  0   
1613            NaN               8                  0   

      YearsSinceLastPromotion  YEARSWITHCURRMANAGER  YearsCurrentRole  
0                          15                    15               NaN  
1                          11                     9               NaN  
2                          11                    15               NaN  
3                           5                     6               NaN  
4                           2                     8               NaN  
...                       ...                   ...               ...  
1609                        3                     7               NaN  
1610                        0                     8               NaN  
1611                        0                     7               NaN  
1612                        0                     7               NaN  
1613                        0                     7               NaN  

[1614 rows x 6 columns]

#  Years with current manager

In [ ]:
data.YEARSWITHCURRMANAGER.isnull().sum()

0

In [ ]:
data.YEARSWITHCURRMANAGER.duplicated().sum()

1596

In [ ]:
data.YEARSWITHCURRMANAGER.value_counts()

2     380
0     270
7     267
3     148
8     115
4     104
1      84
9      70
5      36
10     31
6      30
11     22
12     20
13     16
17      8
15      5
14      5
16      3
Name: YEARSWITHCURRMANAGER, dtype: int64

## CompanyStandards
- Salary 
- AverageSalary // Propuesta de nueva columna para hacer la media de ingresos de los empleados
- StandardHours

# Salary

In [ ]:
data.Salary

0       1000000000$
1       1000000000$
2       1000000000$
3       1000000000$
4       1000000000$
           ...     
1609    1000000000$
1610    1000000000$
1611    1000000000$
1612    1000000000$
1613    1000000000$
Name: Salary, Length: 1614, dtype: object

#  Standar hours

In [ ]:
data.StandardHours

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
1609    NaN
1610    NaN
1611    NaN
1612    NaN
1613    NaN
Name: StandardHours, Length: 1614, dtype: object

In [ ]:
data.StandardHours.isnull().sum()

1195

In [ ]:
data.StandardHours.duplicated().sum()

1612

In [ ]:
data.StandardHours.unique()

array([nan, '80,0'], dtype=object)

In [ ]:
data.isna().sum()/data.shape[0]*100

Unnamed: 0                    0.000000
Age                           0.000000
Attrition                     0.000000
BusinessTravel               47.831475
DailyRate                     0.000000
Department                   81.288724
DistanceFromHome              0.000000
Education                     0.000000
EducationField               46.158612
employeecount                 0.000000
employeenumber               26.703841
EnvironmentSatisfaction       0.000000
Gender                        0.000000
HourlyRate                    0.000000
JobInvolvement                0.000000
JobLevel                      0.000000
JobRole                       0.000000
JobSatisfaction               0.000000
MaritalStatus                40.334572
MonthlyIncome                52.230483
MonthlyRate                   0.000000
NUMCOMPANIESWORKED            0.000000
Over18                       55.824040
OverTime                     41.883519
PercentSalaryHike             0.000000
PerformanceRating        

In [ ]:
data.describe().T

count          mean          std     min      25%  \
Unnamed: 0                1614.0    806.500000   466.065982     0.0   403.25   
DistanceFromHome          1614.0      4.527261    14.591913   -49.0     2.00   
Education                 1614.0      2.925031     1.022357     1.0     2.00   
employeecount             1614.0      1.000000     0.000000     1.0     1.00   
EnvironmentSatisfaction   1614.0      4.294919     6.993559     1.0     2.00   
Gender                    1614.0      0.398389     0.489718     0.0     0.00   
JobInvolvement            1614.0      2.739777     0.711567     1.0     2.00   
JobLevel                  1614.0      2.068154     1.101344     1.0     1.00   
JobSatisfaction           1614.0      2.738538     1.106163     1.0     2.00   
MonthlyRate               1614.0  14284.495663  7110.414585  2094.0  8001.00   
NUMCOMPANIESWORKED        1614.0      2.673482     2.506152     0.0     1.00   
PercentSalaryHike         1614.0     15.165428     3.648610    11.0    12.00   
RelationshipSatisfaction  1614.0      2.704461     1.079031     1.0     2.00   
StockOptionLevel          1614.0      0.791202     0.842396     0.0     0.00   
TrainingTimesLastYear     1614.0      2.809789     1.297765     0.0     2.00   
YearsAtCompany            1614.0      7.132590     6.124237     0.0     3.00   
YearsSinceLastPromotion   1614.0      2.245973     3.235665     0.0     0.00   
YEARSWITHCURRMANAGER      1614.0      4.220570     3.562695     0.0     2.00   
DateBirth                 1614.0   1986.076208     9.101332  1963.0  1980.00   
NUMBERCHILDREN               0.0           NaN          NaN     NaN      NaN   

                              50%       75%      max  
Unnamed: 0                  806.5   1209.75   1613.0  
DistanceFromHome              5.0     11.00     29.0  
Education                     3.0      4.00      5.0  
employeecount                 1.0      1.00      1.0  
EnvironmentSatisfaction       3.0      4.00     49.0  
Gender                        0.0      1.00      1.0  
JobInvolvement                3.0      3.00      4.0  
JobLevel                      2.0      3.00      5.0  
JobSatisfaction               3.0      4.00      4.0  
MonthlyRate               14248.5  20364.00  26999.0  
NUMCOMPANIESWORKED            2.0      4.00      9.0  
PercentSalaryHike            14.0     18.00     25.0  
RelationshipSatisfaction      3.0      4.00      4.0  
StockOptionLevel              1.0      1.00      3.0  
TrainingTimesLastYear         3.0      3.00      6.0  
YearsAtCompany                5.0      9.00     40.0  
YearsSinceLastPromotion       1.0      3.00     15.0  
YEARSWITHCURRMANAGER          3.0      7.00     17.0  
DateBirth                  1987.0   1993.00   2005.0  
NUMBERCHILDREN                NaN       NaN      NaN