In [2]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv ('files/HR_RAW_DATA.csv', index_col = 0)

In [6]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'employeecount',
       'employeenumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NUMCOMPANIESWORKED',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TOTALWORKINGYEARS', 'TrainingTimesLastYear', 'WORKLIFEBALANCE',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YEARSWITHCURRMANAGER', 'SameAsMonthlyIncome', 'DateBirth', 'Salary',
       'RoleDepartament', 'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [10]:
data['Age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53',
       '43', '60', '32', '37', '49', '39', '50', '44', '30',
       'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28',
       '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24',
       'thirty', '23', '22', '21', '20', 'twenty-six', '19',
       'thirty-seven', '18', 'thirty-two', 'twenty-four'], dtype=object)

In [11]:
data['Attrition'].unique()

array(['No', 'Yes'], dtype=object)

In [14]:
data['BusinessTravel'].unique()

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [15]:
data['DailyRate'].unique()
#salario diario, borrar $

array(['684,0$', '699,0$', '532,0$', '359,0$', '1319,0$', '117,0$',
       '1435,0$', '635,0$', '1276,0$', '840,0$', '247,0$', '1369,0$',
       '201,0$', '1360,0$', '692,0$', '1398,0$', '286,0$', '1402,0$',
       '819,0$', '884,0$', '1238,0$', '515,0$', '1223,0$', '202,0$',
       '928,0$', '607,0$', '266,0$', '429,0$', '589,0$', 'nan$',
       '1180,0$', '1282,0$', '776,0$', '665,0$', '526,0$', '1034,0$',
       '1403,0$', '1499,0$', '580,0$', '859,0$', '263,0$', '1376,0$',
       '885,0$', '1003,0$', '1321,0$', '394,0$', '1372,0$', '1333,0$',
       '228,0$', '737,0$', '823,0$', '667,0$', '301,0$', '573,0$',
       '1329,0$', '630,0$', '1063,0$', '1017,0$', '1296,0$', '939,0$',
       '1355,0$', '1448,0$', '200,0$', '1202,0$', '404,0$', '208,0$',
       '813,0$', '465,0$', '1189,0$', '1001,0$', '1394,0$', '161,0$',
       '288,0$', '682,0$', '1354,0$', '147,0$', '119,0$', '1413,0$',
       '452,0$', '334,0$', '1132,0$', '982,0$', '480,0$', '1099,0$',
       '672,0$', '1379,0$', '58

In [16]:
data['Department'].unique()
#borrar espacios en blanco

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [17]:
data['DistanceFromHome'].unique()
#cambio - por +

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [18]:
data['Education'].unique()

array([3, 4, 2, 1, 5])

In [19]:
data['EducationField'].unique()

array([nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other',
       'Marketing', 'Human Resources'], dtype=object)

In [22]:
data['employeecount'].unique()
#¿se puede borrar?

array([1])

In [27]:
data['employeenumber']
#deberia ser in int, donde hay NaN, hay que reasignar un id, ¿por qué esos números? ¿podemos sustituirlos por nums con más lógica?

0       162,0
1       259,0
2       319,0
3         NaN
4         NaN
        ...  
1609    967,0
1610    972,0
1611      NaN
1612    990,0
1613      NaN
Name: employeenumber, Length: 1614, dtype: object

In [28]:
data['EnvironmentSatisfaction'].unique()
# tendría que ser del 1 al 4 ¿son porcentajes?¿son floats convertidos a int?
#podemos cambiarlo a strings que sean más claros?
#escala de Likert

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [29]:
data['Gender'].unique()
#¿se puede cambiar por male/female?

array([0, 1])

In [30]:
data['HourlyRate'].unique()
#salario por hora por empleado
# ¿qué hacer con Not available?

array(['51', '65', '58', '82', '45', '99', '91', '64', '55', '68', '49',
       '61', '79', '31', '69', '48', '80', '74', '98', '59', '33', '56',
       '66', '57', '53', '87', '81', '84', '32', '41', '92', '47',
       'Not Available', '43', '86', '30', '42', '88', '96', '67', '62',
       '72', '78', '89', '52', '50', '90', '37', '94', '76', '60', '46',
       '83', '100', '40', '97', '54', '75', '39', '85', '63', '44', '93',
       '36', '35', '73', '71', '70', '38', '77', '95', '34'], dtype=object)

In [31]:
data['JobInvolvement'].unique()
#nivel de implicación 

array([3, 2, 4, 1])

In [32]:
data['JobLevel'].unique()
#¿a qué corresponde cada nivel?
#¿se puede cambiar por string?

array([5, 4, 3, 2, 1])

In [35]:
data['JobRole']
#poner bonito
#hacer .lower y .strip

0             resEArch DIREcToR 
1                       ManAGeR 
2                       ManaGER 
3             ReseArCH DIrECtOr 
4               sAleS EXECUtIve 
                  ...           
1609            saLEs ExeCUTiVe 
1610      LAboRaTOry tECHNiCIAn 
1611            sAlES ExECUTivE 
1612            SaLes ExecUtIVe 
1613     mAnUfactURInG DiRECTOr 
Name: JobRole, Length: 1614, dtype: object

In [37]:
data['JobSatisfaction'].unique()
# ¿a qué corresponde cada índice?
# ¿podemos cambiar por strigs?

array([3, 4, 1, 2])

In [38]:
data['MaritalStatus'].unique()
# unificar criterios, nan a None

array([nan, 'Married', 'Divorced', 'Single', 'divorced', 'Marreid'],
      dtype=object)

In [39]:
data['MonthlyIncome'].unique()
#salario mensual
#pasar a int

array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841

In [41]:
data['MonthlyRate']
#tasa mensual del empleado, ¿impuestos?¿incentivos?

0        6462
1        5678
2        4933
3       26703
4        7739
        ...  
1609     5518
1610    23163
1611     2560
1612    25952
1613    24208
Name: MonthlyRate, Length: 1614, dtype: int64

In [45]:
data['NUMCOMPANIESWORKED'].unique()
#número de compañías en las que ha trabajado cada trabajador

array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6])

In [47]:
data['Over18']
#comparar con la columna de edad para ver si es correcto

0         Y
1       NaN
2       NaN
3         Y
4         Y
       ... 
1609      Y
1610    NaN
1611    NaN
1612    NaN
1613      Y
Name: Over18, Length: 1614, dtype: object

In [48]:
data['OverTime'].unique()
#horas extras
#nan por none

array(['No', nan, 'Yes'], dtype=object)

In [49]:
data['PercentSalaryHike'].unique()
#El porcentaje de aumento salarial del empleado ¿es anual?¿desde que entró en la empresa?

array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18])

In [50]:
data['PerformanceRating'].unique()
#calificación del rendimieto del empleado ¿qué significan?¿es del 1 al 4?

array(['3,0', '4,0', nan], dtype=object)

In [51]:
data['RelationshipSatisfaction'].unique()
#Nivel de satisfacción en las relaciones interpersonales del empleado.
#cambiar por un string?

array([3, 1, 4, 2])

In [52]:
data['StandardHours'].unique()
# ¿qué significa? 

array([nan, '80,0'], dtype=object)

In [53]:
data['StockOptionLevel'].unique()
# Nivel de opciones de compra de acciones del empleado.

array([0, 1, 2, 3])

In [55]:
data['TOTALWORKINGYEARS'].unique()
# Total de años de experiencia laboral del empleado.
#cambiar a int


array([nan, '34,0', '22,0', '28,0', '20,0', '21,0', '33,0', '40,0',
       '18,0', '25,0', '15,0', '17,0', '26,0', '16,0', '24,0', '14,0',
       '23,0', '27,0', '19,0', '11,0', '38,0', '37,0', '13,0', '12,0',
       '29,0', '10,0', '36,0', '35,0', '9,0', '31,0', '32,0', '8,0',
       '7,0', '30,0', '6,0', '5,0', '4,0', '3,0', '2,0', '1,0', '0,0'],
      dtype=object)

In [56]:
data['TrainingTimesLastYear'].unique()
# Número de veces que el empleado recibió capacitación el año pasado.
# ¿numero de cursos?

array([5, 3, 2, 0, 1, 4, 6])

In [57]:
data['WORKLIFEBALANCE'].unique()
#pasar a int
#rango del 1 al 4

array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

In [59]:
data['YearsAtCompany'].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

In [61]:
data['YearsInCurrentRole'].unique()
#pasar a int 


array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [62]:
data['YearsSinceLastPromotion'].unique()
#Años desde la última promoción del empleado.

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

In [64]:
data['YEARSWITHCURRMANAGER'].unique()
# Años que el empleado ha estado bajo la supervisión del actual gerente.

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])

In [65]:
data['SameAsMonthlyIncome'].unique()
#Ingresos mensuales del empleado.
#hay que contrastar con MonthlyIncome y ver si coinciden

array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841

In [66]:
data['DateBirth'].unique()
#relacion con age y con mayores de 18?

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])

In [68]:
data['Salary']
#lo que destina la empresa a pagar sueldos. No tiene que ir en cada fila, ya que es un total de salarios.
#coincide con el total de la suma de los salarios

0       1000000000$
1       1000000000$
2       1000000000$
3       1000000000$
4       1000000000$
           ...     
1609    1000000000$
1610    1000000000$
1611    1000000000$
1612    1000000000$
1613    1000000000$
Name: Salary, Length: 1614, dtype: object

In [69]:
data['RoleDepartament'].unique()
# El departamento y el rol del empleado.
# limpieza .lower()
# ya tenemos jobrole y department
# ¿coincide con jobrole y department? si coinciden, ¿podemos quitar esta columna?

array([nan, ' ManaGER  -  Research & Development ',
       ' MANAger  -  Research & Development ',
       ' heaLtHcArE repResENtATiVe  -  Research & Development ',
       ' saLEs exEcutIVe  -  Sales ', ' Sales ExECuTIVe  -  Sales ',
       ' heALthCArE RePResEntaTIVe  -  Research & Development ',
       ' lABORAtOry tECHnIcIan  -  Research & Development ',
       ' ManufactUrINg DiReCTOr  -  Research & Development ',
       ' SaleS eXEcUtIVE  -  Sales ',
       ' HEaLthcaRe rEprEsEnTAtiVe  -  Research & Development ',
       ' rESeArCH sCientIST  -  Research & Development ',
       ' healTHCAre rePREseNtATiVE  -  Research & Development ',
       ' mANaGer  -  Research & Development ',
       ' HEAltHCaRe REPreseNTatIve  -  Research & Development ',
       ' SaLeS eXECUTivE  -  Sales ',
       ' reSeARCH SCIEnTiST  -  Research & Development ',
       ' ReSearch DiRecTOR  -  Research & Development ',
       ' resEaRCh SciEnTist  -  Research & Development ',
       ' hUmaN REsoUrCes  -  H

In [71]:
data['NUMBERCHILDREN']
#¿se puede borrar?

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1609   NaN
1610   NaN
1611   NaN
1612   NaN
1613   NaN
Name: NUMBERCHILDREN, Length: 1614, dtype: float64

In [72]:
data['RemoteWork'].unique()
# unificar

array(['Yes', '1', 'False', '0', 'True'], dtype=object)