In [1]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_csv ('../files/HR_RAW_DATA.csv', index_col = 0)

## EmploymentGeneral
- EmployeeID (FK)
- Attrition
- OverTime
- DistanceFromHome
- RemoteWork
- BusinessTravel
- TrainingTimesLastYear

## EmploymentTeams
- EmployeeID (FK)
- Department
- JobRole
- JobLevel

1 - Analisis de nulos

In [13]:
data["Attrition"].isnull().sum()

0

In [16]:
data["OverTime"].isnull().sum() ?

676

In [17]:
data["DistanceFromHome"].isnull().sum()

0

In [20]:
data["RemoteWork"].isnull().sum()

0

In [21]:
data["TrainingTimesLastYear"].isnull().sum()

0

In [23]:
data["Department"].isnull() ¿? 

0        True
1        True
2       False
3        True
4        True
        ...  
1609     True
1610     True
1611     True
1612     True
1613     True
Name: Department, Length: 1614, dtype: bool

In [24]:
data["JobRole"].isnull() 

0       False
1       False
2       False
3       False
4       False
        ...  
1609    False
1610    False
1611    False
1612    False
1613    False
Name: JobRole, Length: 1614, dtype: bool

In [25]:
data["JobLevel"].isnull() 

0       False
1       False
2       False
3       False
4       False
        ...  
1609    False
1610    False
1611    False
1612    False
1613    False
Name: JobLevel, Length: 1614, dtype: bool

2 - Analisis duplicados

In [33]:
data["Attrition"].duplicated().sum()

1612

In [34]:
data["OverTime"].duplicated().sum()

1611

In [35]:
data["DistanceFromHome"].duplicated().sum()

1545

In [36]:
data["RemoteWork"].duplicated().sum()

1609

In [37]:
data["BusinessTravel"].duplicated().sum()

1610

In [38]:
data["TrainingTimesLastYear"].duplicated().sum()

1607

In [39]:
data["Department"].duplicated().sum()

1610

In [40]:
data["JobRole"].duplicated().sum()

35

In [41]:
data["JobLevel"].duplicated().sum()

1609

In [42]:
data.duplicated().sum() #en general, no hay filas duplicadas en la tabla. 

0

3- Exploración de valores únicos por columna

In [43]:
data["Attrition"].unique()

array(['No', 'Yes'], dtype=object)

In [44]:
data["OverTime"].unique() 

array(['No', nan, 'Yes'], dtype=object)

In [47]:
data["DistanceFromHome"].unique() #revisar valores negativos

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [49]:
data["RemoteWork"].unique() #inconsistencia en respuestas

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [50]:
data["BusinessTravel"].unique() 

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [51]:
data["TrainingTimesLastYear"].unique() 

array([5, 3, 2, 0, 1, 4, 6])

In [52]:
data["Department"].unique() 

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [53]:
data["JobRole"].unique() #limpiar datos para corregir errores tipográficos

array([' resEArch DIREcToR ', ' ManAGeR ', ' ManaGER ', ...,
       ' sAlES ExECUTivE ', ' SaLes ExecUtIVe ',
       ' mAnUfactURInG DiRECTOr '], dtype=object)

In [54]:
data["JobLevel"].unique() #investigar que categoría es cada una de ellas. Aparentemente es una variable categorica, ver como se relaciona con otras columnas. 

array([5, 4, 3, 2, 1])

4 -  Analisis de caracteristicas employeenumber 

In [65]:
data["employeenumber"]

0       162,0
1       259,0
2       319,0
3         NaN
4         NaN
        ...  
1609    967,0
1610    972,0
1611      NaN
1612    990,0
1613      NaN
Name: employeenumber, Length: 1614, dtype: object

In [61]:
data["employeenumber"].isnull().sum()

431

In [62]:
data["employeenumber"].notnull().duplicated().sum()

1612

In [66]:
data["employeenumber"].notnull().duplicated()

0       False
1        True
2        True
3       False
4        True
        ...  
1609     True
1610     True
1611     True
1612     True
1613     True
Name: employeenumber, Length: 1614, dtype: bool

In [64]:
data["employeenumber"].notnull().duplicated().value_counts()


True     1612
False       2
Name: employeenumber, dtype: int64

In [77]:
print(data["employeenumber"].value_counts())

482,0     2
530,0     2
507,0     2
517,0     2
522,0     2
         ..
161,0     1
164,0     1
190,0     1
194,0     1
2040,0    1
Name: employeenumber, Length: 1079, dtype: int64


In [74]:
data[data["employeenumber"] == "482,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
883   57        No  travel_rarely    593,0$        NaN                 1   
1524  57        No  travel_rarely    593,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
883           4        Medical              1          482,0  ...   
1524          4        Medical              1          482,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
883                3                 NaN                       1   
1524               3                 NaN                       1   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
883                      2               6755,0      1966  1000000000$   
1524                     2               6755,0      1966  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
883              NaN            NaN           1  
1524             NaN            NaN       False  

[2 rows x 41 columns]

In [75]:
data[data["employeenumber"] == "530,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
897   31        No  travel_rarely    329,0$        NaN                 1   
1538  31        No  travel_rarely    329,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
897           2            NaN              1          530,0  ...   
1538          2            NaN              1          530,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
897                4                 NaN                       3   
1538               4                 NaN                       3   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
897                      2               2218,0      1992  1000000000$   
1538                     2               2218,0      1992  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
897              NaN            NaN           0  
1538             NaN            NaN           1  

[2 rows x 41 columns]

In [82]:
data[data["employeenumber"] == "530,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
897   31        No  travel_rarely    329,0$        NaN                 1   
1538  31        No  travel_rarely    329,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
897           2            NaN              1          530,0  ...   
1538          2            NaN              1          530,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
897                4                 NaN                       3   
1538               4                 NaN                       3   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
897                      2               2218,0      1992  1000000000$   
1538                     2               2218,0      1992  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
897              NaN            NaN           0  
1538             NaN            NaN           1  

[2 rows x 41 columns]