In [2]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv ('../files/HR_RAW_DATA.csv', index_col = 0)
data

Age Attrition BusinessTravel DailyRate                Department  \
0     51        No            NaN    684,0$                       NaN   
1     52        No            NaN    699,0$                       NaN   
2     42        No  travel_rarely    532,0$   Research & Development    
3     47        No  travel_rarely    359,0$                       NaN   
4     46        No            NaN   1319,0$                       NaN   
...   ..       ...            ...       ...                       ...   
1609  36       Yes  travel_rarely    530,0$                       NaN   
1610  45        No     non-travel    805,0$                       NaN   
1611  39        No  travel_rarely    903,0$                       NaN   
1612  36        No     non-travel   1229,0$                       NaN   
1613  46        No            NaN    566,0$                       NaN   

      DistanceFromHome  Education    EducationField  employeecount  \
0                    6          3               NaN              1   
1                    1          4     Life Sciences              1   
2                    4          2  Technical Degree              1   
3                    2          4           Medical              1   
4                    3          3  Technical Degree              1   
...                ...        ...               ...            ...   
1609                 3          1     Life Sciences              1   
1610                 4          2               NaN              1   
1611               -13          5               NaN              1   
1612                 8          4  Technical Degree              1   
1613                 7          2           Medical              1   

     employeenumber  ...  YearsAtCompany  YearsInCurrentRole  \
0             162,0  ...              20                 NaN   
1             259,0  ...              33                 NaN   
2             319,0  ...              22                 NaN   
3               NaN  ...              20                 NaN   
4               NaN  ...              19                 NaN   
...             ...  ...             ...                 ...   
1609          967,0  ...              16                 NaN   
1610          972,0  ...               9                 NaN   
1611            NaN  ...               8                 NaN   
1612          990,0  ...               7                 NaN   
1613            NaN  ...               8                 NaN   

     YearsSinceLastPromotion  YEARSWITHCURRMANAGER  SameAsMonthlyIncome  \
0                         15                    15              19537,0   
1                         11                     9              19999,0   
2                         11                    15              19232,0   
3                          5                     6              17169,0   
4                          2                     8                  NaN   
...                      ...                   ...                  ...   
1609                       3                     7              10325,0   
1610                       0                     8               4447,0   
1611                       0                     7                  NaN   
1612                       0                     7                  NaN   
1613                       0                     7              10845,0   

     DateBirth       Salary                       RoleDepartament  \
0         1972  1000000000$                                   NaN   
1         1971  1000000000$                                   NaN   
2         1981  1000000000$   ManaGER  -  Research & Development    
3         1976  1000000000$                                   NaN   
4         1977  1000000000$                                   NaN   
...        ...          ...                                   ...   
1609      1987  1000000000$                                   NaN   
1610      1978  1000000000$                                   NaN

In [6]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'employeecount',
       'employeenumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NUMCOMPANIESWORKED',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TOTALWORKINGYEARS', 'TrainingTimesLastYear', 'WORKLIFEBALANCE',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YEARSWITHCURRMANAGER', 'SameAsMonthlyIncome', 'DateBirth', 'Salary',
       'RoleDepartament', 'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [53]:
surveys = data.loc [:, ['employeenumber', 'EnvironmentSatisfaction', 'JobSatisfaction', 'RelationshipSatisfaction', 'WORKLIFEBALANCE', 'JobInvolvement', 'PerformanceRating' ]]
surveys 

employeenumber  EnvironmentSatisfaction  JobSatisfaction  \
0             162,0                        1                3   
1             259,0                        3                3   
2             319,0                        3                4   
3               NaN                        1                3   
4               NaN                        1                1   
...             ...                      ...              ...   
1609          967,0                        3                4   
1610          972,0                        3                2   
1611            NaN                       13                3   
1612          990,0                        1                4   
1613            NaN                        4                3   

      RelationshipSatisfaction WORKLIFEBALANCE  JobInvolvement  \
0                            3             3,0               3   
1                            1             3,0               2   
2                            4             NaN               3   
3                            2             NaN               3   
4                            4             3,0               4   
...                        ...             ...             ...   
1609                         1             3,0               2   
1610                         2             2,0               3   
1611                         4             3,0               4   
1612                         4             3,0               3   
1613                         2             3,0               3   

     PerformanceRating  
0                  3,0  
1                  3,0  
2                  3,0  
3                  3,0  
4                  3,0  
...                ...  
1609               NaN  
1610               3,0  
1611               3,0  
1612               NaN  
1613               3,0  

[1614 rows x 7 columns]

In [24]:
surveys.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1614 entries, 0 to 1613
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   employeenumber            1183 non-null   object
 1   EnvironmentSatisfaction   1614 non-null   int64 
 2   JobSatisfaction           1614 non-null   int64 
 3   RelationshipSatisfaction  1614 non-null   int64 
 4   WORKLIFEBALANCE           1506 non-null   object
 5   JobInvolvement            1614 non-null   int64 
 6   PerformanceRating         1419 non-null   object
dtypes: int64(4), object(3)
memory usage: 100.9+ KB


## 'employeenumber'

In [11]:
surveys ['employeenumber'].describe().T
#variable categórica que debería ser numérica

count      1183
unique     1079
top       482,0
freq          2
Name: employeenumber, dtype: object

In [39]:
surveys ['employeenumber'].isnull().sum()

431

In [30]:
employee_numbers_notnull = surveys.loc[surveys['employeenumber'].notnull() , ['employeenumber']]
employee_numbers_notnull

employeenumber
0             162,0
1             259,0
2             319,0
5            1900,0
6              81,0
...             ...
1606          956,0
1608          966,0
1609          967,0
1610          972,0
1612          990,0

[1183 rows x 1 columns]

In [38]:
employee_numbers_notnull['employeenumber'].duplicated().sum()

104

In [67]:
surveys['employeenumber'].isna().sum()/surveys['employeenumber'].shape[0]*100
#tenemos un 26 % de nulos

26.703841387856258

## 'EnvironmentSatisfaction'
Nivel de satisfacción del empleado en relación con su entorno de trabajo. Con valores que estan comprendidos entre el 1 y el 4, siendo el 4 el nivel de máxima satisfacción.

In [25]:
surveys ['EnvironmentSatisfaction'].describe().T
#variable numérica

count    1614.000000
mean        4.294919
std         6.993559
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        49.000000
Name: EnvironmentSatisfaction, dtype: float64

In [41]:
surveys ['EnvironmentSatisfaction'].isnull().sum()
#no hay nulos

0

In [27]:
surveys['EnvironmentSatisfaction'].unique()
# los valores están descritos del 1 al 50, no del 1 al 4. Probablemente sea porque lo han querido hacer como decimal pero no le han puesto el . 
# no podemos sacar conclusiones con los datos de esta manera

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

## 'JobSatisfaction'
Nivel de satisfacción del empleado con su trabajo.

In [45]:
surveys ['JobSatisfaction'].describe().T
#variable numérica

count    1614.000000
mean        2.738538
std         1.106163
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: JobSatisfaction, dtype: float64

In [46]:
surveys ['JobSatisfaction'].isnull().sum()
#no tenemos valores nulos 

0

In [47]:
surveys['JobSatisfaction'].unique()
#en este caso los valores están correctos, ya que están clasificados del 1 al 4

array([3, 4, 1, 2])

## 'RelationshipSatisfaction'
Nivel de satisfacción en las relaciones interpersonales del empleado.

In [48]:
surveys['RelationshipSatisfaction'].unique()
#en este caso los valores están correctos, ya que están clasificados del 1 al 4

array([3, 1, 4, 2])

In [49]:
surveys ['RelationshipSatisfaction'].describe().T
#variable numérica 

count    1614.000000
mean        2.704461
std         1.079031
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: RelationshipSatisfaction, dtype: float64

In [50]:
surveys ['RelationshipSatisfaction'].isnull().sum()

0

## 'WORKLIFEBALANCE'
Equilibrio entre trabajo y vida personal del empleado.

In [54]:
surveys['WORKLIFEBALANCE'].describe().T
#variable categórica

count     1506
unique       4
top        3,0
freq       913
Name: WORKLIFEBALANCE, dtype: object

In [55]:
surveys['WORKLIFEBALANCE'].unique()
# hay que unificar con las demás

array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

In [56]:
surveys['WORKLIFEBALANCE'].isnull().sum()
#108 nulas que si sumamos a las 1506, dan el total de filas.

108

In [66]:
surveys['WORKLIFEBALANCE'].isna().sum()/surveys['WORKLIFEBALANCE'].shape[0]*100
#tenemos un 7% de nulos

6.691449814126393

## 'JobInvolvement'
Nivel de implicación del empleado en su trabajo.

In [57]:
surveys['JobInvolvement'].describe().T
#variable numérica

count    1614.000000
mean        2.739777
std         0.711567
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         4.000000
Name: JobInvolvement, dtype: float64

In [58]:
surveys['JobInvolvement'].unique()
# correctos: del 1 al 4 

array([3, 2, 4, 1])

In [59]:
surveys['JobInvolvement'].isnull().sum()
#no tenemos nulos

0

## 'PerformanceRating'
Calificación de rendimiento del empleado.

In [60]:
surveys['PerformanceRating'].describe().T
#variable categórica

count     1419
unique       2
top        3,0
freq      1205
Name: PerformanceRating, dtype: object

In [61]:
surveys['PerformanceRating'].unique()
#sólo tenemos valores 3 y 4

array(['3,0', '4,0', nan], dtype=object)

In [62]:
surveys['PerformanceRating'].isnull().sum()
#tenemos 195 nulos 

195

In [64]:
surveys['PerformanceRating'].isna().sum()/surveys['PerformanceRating'].shape[0]*100
#tenemos un 12% de nulos

12.0817843866171

In [65]:
surveys.isna().sum()/surveys.shape[0]*100

employeenumber              26.703841
EnvironmentSatisfaction      0.000000
JobSatisfaction              0.000000
RelationshipSatisfaction     0.000000
WORKLIFEBALANCE              6.691450
JobInvolvement               0.000000
PerformanceRating           12.081784
dtype: float64