In [12]:
import pandas as pd
import numpy as np

In [13]:
data = pd.read_csv ('../../files/HR_RAW_DATA.csv', index_col = 0)

## EmploymentGeneral
- EmployeeID (FK)
- Attrition
- OverTime
- DistanceFromHome
- RemoteWork
- BusinessTravel
- TrainingTimesLastYear

## EmploymentTeams
- EmployeeID (FK)
- Department
- JobRole
- JobLevel

1 - Analisis de nulos

In [14]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'employeecount',
       'employeenumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NUMCOMPANIESWORKED',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TOTALWORKINGYEARS', 'TrainingTimesLastYear', 'WORKLIFEBALANCE',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YEARSWITHCURRMANAGER', 'SameAsMonthlyIncome', 'DateBirth', 'Salary',
       'RoleDepartament', 'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [59]:
columnas_patri = ["Attrition", "OverTime", "DistanceFromHome", "RemoteWork", "BusinessTravel", "TrainingTimesLastYear", "Department", "JobRole", "JobLevel"]

In [16]:
data["Attrition"].isnull().sum()

0

In [17]:
data["OverTime"].isnull().sum() 

676

In [18]:
data["DistanceFromHome"].isnull().sum()

0

In [19]:
data["RemoteWork"].isnull().sum()

0

In [20]:
data["TrainingTimesLastYear"].isnull().sum()

0

In [21]:
data["Department"].isnull() 

0        True
1        True
2       False
3        True
4        True
        ...  
1609     True
1610     True
1611     True
1612     True
1613     True
Name: Department, Length: 1614, dtype: bool

In [22]:
data["JobRole"].isnull() 

0       False
1       False
2       False
3       False
4       False
        ...  
1609    False
1610    False
1611    False
1612    False
1613    False
Name: JobRole, Length: 1614, dtype: bool

In [23]:
data["JobLevel"].isnull() 

0       False
1       False
2       False
3       False
4       False
        ...  
1609    False
1610    False
1611    False
1612    False
1613    False
Name: JobLevel, Length: 1614, dtype: bool

2 - Analisis duplicados

In [24]:
data["Attrition"].duplicated().sum()

1612

In [25]:
data["OverTime"].duplicated().sum()

1611

In [26]:
data["DistanceFromHome"].duplicated().sum()

1545

In [27]:
data["RemoteWork"].duplicated().sum()

1609

In [28]:
data["BusinessTravel"].duplicated().sum()

1610

In [29]:
data["TrainingTimesLastYear"].duplicated().sum()

1607

In [30]:
data["Department"].duplicated().sum()

1610

In [31]:
data["JobRole"].duplicated().sum()

35

In [32]:
data["JobLevel"].duplicated().sum()

1609

In [33]:
data.duplicated().sum() #en general, no hay filas duplicadas en la tabla. 

0

3- Exploración de valores únicos por columna

In [34]:
data["Attrition"].unique()

array(['No', 'Yes'], dtype=object)

In [35]:
data["OverTime"].unique() 

array(['No', nan, 'Yes'], dtype=object)

In [36]:
data["DistanceFromHome"].unique() #revisar valores negativos

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [37]:
data["RemoteWork"].unique() #inconsistencia en respuestas

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [38]:
data["BusinessTravel"].unique() 

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [39]:
data["TrainingTimesLastYear"].unique() 

array([5, 3, 2, 0, 1, 4, 6])

In [40]:
data["Department"].unique() 

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [41]:
data["JobRole"].unique() #limpiar datos para corregir errores tipográficos

array([' resEArch DIREcToR ', ' ManAGeR ', ' ManaGER ', ...,
       ' sAlES ExECUTivE ', ' SaLes ExecUtIVe ',
       ' mAnUfactURInG DiRECTOr '], dtype=object)

In [42]:
data["JobLevel"].unique() #investigar que categoría es cada una de ellas. Aparentemente es una variable categorica, ver como se relaciona con otras columnas. 

array([5, 4, 3, 2, 1])

In [43]:
data[["JobRole", "JobLevel", "Department"]] #ver criterio 

JobRole  JobLevel                Department
0           resEArch DIREcToR          5                       NaN
1                     ManAGeR          5                       NaN
2                     ManaGER          5   Research & Development 
3           ReseArCH DIrECtOr          4                       NaN
4             sAleS EXECUtIve          4                       NaN
...                        ...       ...                       ...
1609          saLEs ExeCUTiVe          3                       NaN
1610    LAboRaTOry tECHNiCIAn          2                       NaN
1611          sAlES ExECUTivE          3                       NaN
1612          SaLes ExecUtIVe          2                       NaN
1613   mAnUfactURInG DiRECTOr          3                       NaN

[1614 rows x 3 columns]

4 -  Analisis de caracteristicas employeenumber 

In [44]:
data["employeenumber"]

0       162,0
1       259,0
2       319,0
3         NaN
4         NaN
        ...  
1609    967,0
1610    972,0
1611      NaN
1612    990,0
1613      NaN
Name: employeenumber, Length: 1614, dtype: object

In [45]:
data["employeenumber"].isnull().sum()

431

In [46]:
data["employeenumber"].notnull().duplicated().sum()

1612

In [47]:
data["employeenumber"].notnull().duplicated()

0       False
1        True
2        True
3       False
4        True
        ...  
1609     True
1610     True
1611     True
1612     True
1613     True
Name: employeenumber, Length: 1614, dtype: bool

In [48]:
data["employeenumber"].notnull().duplicated().value_counts()


True     1612
False       2
Name: employeenumber, dtype: int64

In [49]:
print(data["employeenumber"].value_counts())

482,0     2
530,0     2
507,0     2
517,0     2
522,0     2
         ..
161,0     1
164,0     1
190,0     1
194,0     1
2040,0    1
Name: employeenumber, Length: 1079, dtype: int64


In [50]:
data[data["employeenumber"] == "482,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
883   57        No  travel_rarely    593,0$        NaN                 1   
1524  57        No  travel_rarely    593,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
883           4        Medical              1          482,0  ...   
1524          4        Medical              1          482,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
883                3                 NaN                       1   
1524               3                 NaN                       1   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
883                      2               6755,0      1966  1000000000$   
1524                     2               6755,0      1966  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
883              NaN            NaN           1  
1524             NaN            NaN       False  

[2 rows x 41 columns]

In [51]:
data[data["employeenumber"] == "530,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
897   31        No  travel_rarely    329,0$        NaN                 1   
1538  31        No  travel_rarely    329,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
897           2            NaN              1          530,0  ...   
1538          2            NaN              1          530,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
897                4                 NaN                       3   
1538               4                 NaN                       3   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
897                      2               2218,0      1992  1000000000$   
1538                     2               2218,0      1992  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
897              NaN            NaN           0  
1538             NaN            NaN           1  

[2 rows x 41 columns]

In [52]:
data[data["employeenumber"] == "530,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
897   31        No  travel_rarely    329,0$        NaN                 1   
1538  31        No  travel_rarely    329,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
897           2            NaN              1          530,0  ...   
1538          2            NaN              1          530,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
897                4                 NaN                       3   
1538               4                 NaN                       3   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
897                      2               2218,0      1992  1000000000$   
1538                     2               2218,0      1992  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
897              NaN            NaN           0  
1538             NaN            NaN           1  

[2 rows x 41 columns]

In [53]:
data['RemoteWork'].unique()
# unificar

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [54]:
#calcular nulos
data['RemoteWork'].isna().sum()/data['RemoteWork'].shape[0]*100

0.0

### Fase 2: Limpieza
Criterios de unificación y limpieza:

- Todos los elementos string en .lower()
- Convertir a integer los datos numéricos siempre y cuando no tengan decimales representativos
- Si nan es una string, cambiarlo a nulo ('nan': float('NaN'))
- Quitar símbolos (como "$" o "%") en los datos y reemplazar "," por "."
- Eliminar los espacios en blanco al principio y final de cada celda (.strip())
- Usar el inglés como idioma vehicular en las tablas y sus datos
- No reordenar las filas
- No eliminar filas
- Revisar que los strings no estén escritos de forma distinta ('married' - 'merried'), faltas de ortografía, etc (unificar los unique)

In [55]:
def binary_unification(columna):

  # diccionario de mapeo
  mapping = {'Yes': 1, 'No': 0, 'False': 0, 'True': 1}

  # replace en funcion del diccionario
  columna = columna.replace(mapping)

  # gestion de posibles errores 
  columna = pd.to_numeric(columna, errors='coerce')

  return data


In [56]:
columna = data['RemoteWork']


In [57]:
binary_unification(columna)

Age Attrition BusinessTravel DailyRate                Department  \
0     51        No            NaN    684,0$                       NaN   
1     52        No            NaN    699,0$                       NaN   
2     42        No  travel_rarely    532,0$   Research & Development    
3     47        No  travel_rarely    359,0$                       NaN   
4     46        No            NaN   1319,0$                       NaN   
...   ..       ...            ...       ...                       ...   
1609  36       Yes  travel_rarely    530,0$                       NaN   
1610  45        No     non-travel    805,0$                       NaN   
1611  39        No  travel_rarely    903,0$                       NaN   
1612  36        No     non-travel   1229,0$                       NaN   
1613  46        No            NaN    566,0$                       NaN   

      DistanceFromHome  Education    EducationField  employeecount  \
0                    6          3               NaN              1   
1                    1          4     Life Sciences              1   
2                    4          2  Technical Degree              1   
3                    2          4           Medical              1   
4                    3          3  Technical Degree              1   
...                ...        ...               ...            ...   
1609                 3          1     Life Sciences              1   
1610                 4          2               NaN              1   
1611               -13          5               NaN              1   
1612                 8          4  Technical Degree              1   
1613                 7          2           Medical              1   

     employeenumber  ...  YearsAtCompany  YearsInCurrentRole  \
0             162,0  ...              20                 NaN   
1             259,0  ...              33                 NaN   
2             319,0  ...              22                 NaN   
3               NaN  ...              20                 NaN   
4               NaN  ...              19                 NaN   
...             ...  ...             ...                 ...   
1609          967,0  ...              16                 NaN   
1610          972,0  ...               9                 NaN   
1611            NaN  ...               8                 NaN   
1612          990,0  ...               7                 NaN   
1613            NaN  ...               8                 NaN   

     YearsSinceLastPromotion  YEARSWITHCURRMANAGER  SameAsMonthlyIncome  \
0                         15                    15              19537,0   
1                         11                     9              19999,0   
2                         11                    15              19232,0   
3                          5                     6              17169,0   
4                          2                     8                  NaN   
...                      ...                   ...                  ...   
1609                       3                     7              10325,0   
1610                       0                     8               4447,0   
1611                       0                     7                  NaN   
1612                       0                     7                  NaN   
1613                       0                     7              10845,0   

     DateBirth       Salary                       RoleDepartament  \
0         1972  1000000000$                                   NaN   
1         1971  1000000000$                                   NaN   
2         1981  1000000000$   ManaGER  -  Research & Development    
3         1976  1000000000$                                   NaN   
4         1977  1000000000$                                   NaN   
...        ...          ...                                   ...   
1609      1987  1000000000$                                   NaN   
1610      1978  1000000000$                                   NaN

In [70]:
for columna in columnas_patri:
    df_limpio = data[columna].replace("%", "")

df_limpio

0       5
1       5
2       5
3       4
4       4
       ..
1609    3
1610    2
1611    3
1612    2
1613    3
Name: JobLevel, Length: 1614, dtype: int64