In [190]:
import pandas as pd
import numpy as np

In [191]:
data = pd.read_csv ('../../files/HR_RAW_DATA.csv', index_col = 0)

## EmploymentGeneral
- EmployeeID (FK)
- Attrition
- OverTime
- DistanceFromHome
- RemoteWork
- BusinessTravel
- TrainingTimesLastYear

## EmploymentTeams
- EmployeeID (FK)
- Department
- JobRole
- JobLevel

1 - Analisis de nulos

In [192]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'employeecount',
       'employeenumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NUMCOMPANIESWORKED',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TOTALWORKINGYEARS', 'TrainingTimesLastYear', 'WORKLIFEBALANCE',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YEARSWITHCURRMANAGER', 'SameAsMonthlyIncome', 'DateBirth', 'Salary',
       'RoleDepartament', 'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [193]:
columnas_patri = ["Attrition", "OverTime", "DistanceFromHome", "RemoteWork", "BusinessTravel", "TrainingTimesLastYear", "Department", "JobRole", "JobLevel"]

In [194]:
data[columnas_patri].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1614 entries, 0 to 1613
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   Attrition              1614 non-null   object
 1   OverTime               938 non-null    object
 2   DistanceFromHome       1614 non-null   int64 
 3   RemoteWork             1614 non-null   object
 4   BusinessTravel         842 non-null    object
 5   TrainingTimesLastYear  1614 non-null   int64 
 6   Department             302 non-null    object
 7   JobRole                1614 non-null   object
 8   JobLevel               1614 non-null   int64 
dtypes: int64(3), object(6)
memory usage: 126.1+ KB


In [195]:
data[columnas_patri].head(5)

Attrition OverTime  DistanceFromHome RemoteWork BusinessTravel  \
0        No       No                 6        Yes            NaN   
1        No      NaN                 1          1            NaN   
2        No       No                 4          1  travel_rarely   
3        No      NaN                 2      False  travel_rarely   
4        No       No                 3          0            NaN   

   TrainingTimesLastYear                Department              JobRole  \
0                      5                       NaN   resEArch DIREcToR    
1                      5                       NaN             ManAGeR    
2                      3   Research & Development              ManaGER    
3                      2                       NaN   ReseArCH DIrECtOr    
4                      5                       NaN     sAleS EXECUtIve    

   JobLevel  
0         5  
1         5  
2         5  
3         4  
4         4

In [196]:
data["Attrition"].isnull().sum()

0

In [197]:
data["OverTime"].isnull().sum() 

676

In [198]:
data["DistanceFromHome"].isnull().sum()

0

In [199]:
data["RemoteWork"].isnull().sum()

0

In [200]:
data["TrainingTimesLastYear"].isnull().sum()

0

In [201]:
data["Department"].isnull() 

0        True
1        True
2       False
3        True
4        True
        ...  
1609     True
1610     True
1611     True
1612     True
1613     True
Name: Department, Length: 1614, dtype: bool

In [202]:
data["JobRole"].isnull() 

0       False
1       False
2       False
3       False
4       False
        ...  
1609    False
1610    False
1611    False
1612    False
1613    False
Name: JobRole, Length: 1614, dtype: bool

In [203]:
data["JobLevel"].isnull() 

0       False
1       False
2       False
3       False
4       False
        ...  
1609    False
1610    False
1611    False
1612    False
1613    False
Name: JobLevel, Length: 1614, dtype: bool

2 - Analisis duplicados

In [204]:
data["Attrition"].duplicated().sum()

1612

In [205]:
data["OverTime"].duplicated().sum()

1611

In [206]:
data["DistanceFromHome"].duplicated().sum()

1545

In [207]:
data["RemoteWork"].duplicated().sum()

1609

In [208]:
data["BusinessTravel"].duplicated().sum()

1610

In [209]:
data["TrainingTimesLastYear"].duplicated().sum()

1607

In [210]:
data["Department"].duplicated().sum()

1610

In [211]:
data["JobRole"].duplicated().sum()

35

In [212]:
data["JobLevel"].duplicated().sum()

1609

In [213]:
data.duplicated().sum() #en general, no hay filas duplicadas en la tabla. 

0

3- Exploración de valores únicos por columna

In [214]:
data["Attrition"].unique()

array(['No', 'Yes'], dtype=object)

In [215]:
data["OverTime"].unique() 

array(['No', nan, 'Yes'], dtype=object)

In [216]:
data["DistanceFromHome"].unique() #revisar valores negativos

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [217]:
data["RemoteWork"].unique() #inconsistencia en respuestas

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [218]:
data["BusinessTravel"].unique() 

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [219]:
data["TrainingTimesLastYear"].unique() 

array([5, 3, 2, 0, 1, 4, 6])

In [220]:
data["Department"].unique() 

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [221]:
data["JobRole"].unique() #limpiar datos para corregir errores tipográficos

array([' resEArch DIREcToR ', ' ManAGeR ', ' ManaGER ', ...,
       ' sAlES ExECUTivE ', ' SaLes ExecUtIVe ',
       ' mAnUfactURInG DiRECTOr '], dtype=object)

In [222]:
data["JobLevel"].unique() #investigar que categoría es cada una de ellas. Aparentemente es una variable categorica, ver como se relaciona con otras columnas. 

array([5, 4, 3, 2, 1])

In [223]:
data[["JobRole", "JobLevel", "Department"]] #ver criterio 

JobRole  JobLevel                Department
0           resEArch DIREcToR          5                       NaN
1                     ManAGeR          5                       NaN
2                     ManaGER          5   Research & Development 
3           ReseArCH DIrECtOr          4                       NaN
4             sAleS EXECUtIve          4                       NaN
...                        ...       ...                       ...
1609          saLEs ExeCUTiVe          3                       NaN
1610    LAboRaTOry tECHNiCIAn          2                       NaN
1611          sAlES ExECUTivE          3                       NaN
1612          SaLes ExecUtIVe          2                       NaN
1613   mAnUfactURInG DiRECTOr          3                       NaN

[1614 rows x 3 columns]

4 -  Analisis de caracteristicas employeenumber 

In [224]:
data["employeenumber"]

0       162,0
1       259,0
2       319,0
3         NaN
4         NaN
        ...  
1609    967,0
1610    972,0
1611      NaN
1612    990,0
1613      NaN
Name: employeenumber, Length: 1614, dtype: object

In [225]:
data["employeenumber"].isnull().sum()

431

In [226]:
data["employeenumber"].notnull().duplicated().sum()

1612

In [227]:
data["employeenumber"].notnull().duplicated()

0       False
1        True
2        True
3       False
4        True
        ...  
1609     True
1610     True
1611     True
1612     True
1613     True
Name: employeenumber, Length: 1614, dtype: bool

In [228]:
data["employeenumber"].notnull().duplicated().value_counts()


True     1612
False       2
Name: employeenumber, dtype: int64

In [229]:
print(data["employeenumber"].value_counts())

482,0     2
530,0     2
507,0     2
517,0     2
522,0     2
         ..
161,0     1
164,0     1
190,0     1
194,0     1
2040,0    1
Name: employeenumber, Length: 1079, dtype: int64


In [230]:
data[data["employeenumber"] == "482,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
883   57        No  travel_rarely    593,0$        NaN                 1   
1524  57        No  travel_rarely    593,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
883           4        Medical              1          482,0  ...   
1524          4        Medical              1          482,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
883                3                 NaN                       1   
1524               3                 NaN                       1   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
883                      2               6755,0      1966  1000000000$   
1524                     2               6755,0      1966  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
883              NaN            NaN           1  
1524             NaN            NaN       False  

[2 rows x 41 columns]

In [231]:
data[data["employeenumber"] == "530,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
897   31        No  travel_rarely    329,0$        NaN                 1   
1538  31        No  travel_rarely    329,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
897           2            NaN              1          530,0  ...   
1538          2            NaN              1          530,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
897                4                 NaN                       3   
1538               4                 NaN                       3   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
897                      2               2218,0      1992  1000000000$   
1538                     2               2218,0      1992  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
897              NaN            NaN           0  
1538             NaN            NaN           1  

[2 rows x 41 columns]

In [232]:
data[data["employeenumber"] == "530,0"] #selecciono ejemplo para analizar información duplicado. Aparentemente se corresponde a la misma persona a diferencia de la columna 'remotework'

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
897   31        No  travel_rarely    329,0$        NaN                 1   
1538  31        No  travel_rarely    329,0$        NaN                 1   

      Education EducationField  employeecount employeenumber  ...  \
897           2            NaN              1          530,0  ...   
1538          2            NaN              1          530,0  ...   

      YearsAtCompany  YearsInCurrentRole YearsSinceLastPromotion  \
897                4                 NaN                       3   
1538               4                 NaN                       3   

      YEARSWITHCURRMANAGER  SameAsMonthlyIncome DateBirth       Salary  \
897                      2               2218,0      1992  1000000000$   
1538                     2               2218,0      1992  1000000000$   

     RoleDepartament NUMBERCHILDREN  RemoteWork  
897              NaN            NaN           0  
1538             NaN            NaN           1  

[2 rows x 41 columns]

In [233]:
data['RemoteWork'].unique()
# unificar

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [234]:
#calcular nulos
data['RemoteWork'].isna().sum()/data['RemoteWork'].shape[0]*100

0.0

### Fase 2: Limpieza
Criterios de unificación y limpieza:

- Convertir a integer los datos numéricos siempre y cuando no tengan decimales representativos
- Si nan es una string, cambiarlo a nulo ('nan': float('NaN'))
- Quitar símbolos (como "$" o "%") en los datos y reemplazar "," por "."
- Eliminar los espacios en blanco al principio y final de cada celda (.strip())
- Usar el inglés como idioma vehicular en las tablas y sus datos
- No reordenar las filas
- No eliminar filas
- Revisar que los strings no estén escritos de forma distinta ('married' - 'merried'), faltas de ortografía, etc (unificar los unique)

In [235]:
def binary_unification(columna):

  # diccionario de mapeo
  mapping = {'Yes': 1, 'No': 0, 'False': 0, 'True': 1}

  # replace en funcion del diccionario
  columna = columna.replace(mapping)

  # gestion de posibles errores 
  columna = pd.to_numeric(columna, errors='coerce')

  return columna


In [236]:
remotework = data['RemoteWork']


In [237]:
unificado = binary_unification(remotework)


In [238]:
data["RemoteWork"] = unificado

In [239]:
minusculas = data["JobRole"].str.lower()
data["JobRole"] = minusculas

In [240]:
data[columnas_patri]

Attrition OverTime  DistanceFromHome  RemoteWork BusinessTravel  \
0           No       No                 6           1            NaN   
1           No      NaN                 1           1            NaN   
2           No       No                 4           1  travel_rarely   
3           No      NaN                 2           0  travel_rarely   
4           No       No                 3           0            NaN   
...        ...      ...               ...         ...            ...   
1609       Yes      NaN                 3           0  travel_rarely   
1610        No      NaN                 4           1     non-travel   
1611        No       No               -13           1  travel_rarely   
1612        No       No                 8           1     non-travel   
1613        No      NaN                 7           0            NaN   

      TrainingTimesLastYear                Department  \
0                         5                       NaN   
1                         5                       NaN   
2                         3   Research & Development    
3                         2                       NaN   
4                         5                       NaN   
...                     ...                       ...   
1609                      6                       NaN   
1610                      5                       NaN   
1611                      3                       NaN   
1612                      3                       NaN   
1613                      3                       NaN   

                       JobRole  JobLevel  
0           research director          5  
1                     manager          5  
2                     manager          5  
3           research director          4  
4             sales executive          4  
...                        ...       ...  
1609          sales executive          3  
1610    laboratory technician          2  
1611          sales executive          3  
1612          sales executive          2  
1613   manufacturing director          3  

[1614 rows x 9 columns]

In [241]:
data["DistanceFromHome"] 

0        6
1        1
2        4
3        2
4        3
        ..
1609     3
1610     4
1611   -13
1612     8
1613     7
Name: DistanceFromHome, Length: 1614, dtype: int64

In [242]:
import numpy as np


In [243]:
def convertir_a_positivo(numero):
    if numero < 0:
        return np.abs(numero)
    else:
        return numero


        


In [244]:
data["DistanceFromHome"] = data["DistanceFromHome"].apply(convertir_a_positivo)

In [245]:
data["DistanceFromHome"] 

0        6
1        1
2        4
3        2
4        3
        ..
1609     3
1610     4
1611    13
1612     8
1613     7
Name: DistanceFromHome, Length: 1614, dtype: int64

In [246]:
data[columnas_patri].head()

Attrition OverTime  DistanceFromHome  RemoteWork BusinessTravel  \
0        No       No                 6           1            NaN   
1        No      NaN                 1           1            NaN   
2        No       No                 4           1  travel_rarely   
3        No      NaN                 2           0  travel_rarely   
4        No       No                 3           0            NaN   

   TrainingTimesLastYear                Department              JobRole  \
0                      5                       NaN   research director    
1                      5                       NaN             manager    
2                      3   Research & Development              manager    
3                      2                       NaN   research director    
4                      5                       NaN     sales executive    

   JobLevel  
0         5  
1         5  
2         5  
3         4  
4         4

In [247]:
data ['OverTime'] = data ['OverTime'].apply (lambda x: 1 if x == 'Yes' else (0 if x == 'No' else np.nan))


In [248]:
data ['OverTime'] = data ['OverTime'].astype ('Int64', errors = 'ignore')

In [249]:
data[columnas_patri].head()

Attrition  OverTime  DistanceFromHome  RemoteWork BusinessTravel  \
0        No         0                 6           1            NaN   
1        No      <NA>                 1           1            NaN   
2        No         0                 4           1  travel_rarely   
3        No      <NA>                 2           0  travel_rarely   
4        No         0                 3           0            NaN   

   TrainingTimesLastYear                Department              JobRole  \
0                      5                       NaN   research director    
1                      5                       NaN             manager    
2                      3   Research & Development              manager    
3                      2                       NaN   research director    
4                      5                       NaN     sales executive    

   JobLevel  
0         5  
1         5  
2         5  
3         4  
4         4

In [250]:
data[columnas_patri].to_csv("transofrmacion_patri", index= False)