In [55]:
import pandas as pd
import numpy as np

In [56]:
#este es nuestro dataframe 
data = pd.read_csv ('../../files/HR_RAW_DATA.csv', index_col = 0)
data

Age Attrition BusinessTravel DailyRate                Department  \
0     51        No            NaN    684,0$                       NaN   
1     52        No            NaN    699,0$                       NaN   
2     42        No  travel_rarely    532,0$   Research & Development    
3     47        No  travel_rarely    359,0$                       NaN   
4     46        No            NaN   1319,0$                       NaN   
...   ..       ...            ...       ...                       ...   
1609  36       Yes  travel_rarely    530,0$                       NaN   
1610  45        No     non-travel    805,0$                       NaN   
1611  39        No  travel_rarely    903,0$                       NaN   
1612  36        No     non-travel   1229,0$                       NaN   
1613  46        No            NaN    566,0$                       NaN   

      DistanceFromHome  Education    EducationField  employeecount  \
0                    6          3               NaN              1   
1                    1          4     Life Sciences              1   
2                    4          2  Technical Degree              1   
3                    2          4           Medical              1   
4                    3          3  Technical Degree              1   
...                ...        ...               ...            ...   
1609                 3          1     Life Sciences              1   
1610                 4          2               NaN              1   
1611               -13          5               NaN              1   
1612                 8          4  Technical Degree              1   
1613                 7          2           Medical              1   

     employeenumber  ...  YearsAtCompany  YearsInCurrentRole  \
0             162,0  ...              20                 NaN   
1             259,0  ...              33                 NaN   
2             319,0  ...              22                 NaN   
3               NaN  ...              20                 NaN   
4               NaN  ...              19                 NaN   
...             ...  ...             ...                 ...   
1609          967,0  ...              16                 NaN   
1610          972,0  ...               9                 NaN   
1611            NaN  ...               8                 NaN   
1612          990,0  ...               7                 NaN   
1613            NaN  ...               8                 NaN   

     YearsSinceLastPromotion  YEARSWITHCURRMANAGER  SameAsMonthlyIncome  \
0                         15                    15              19537,0   
1                         11                     9              19999,0   
2                         11                    15              19232,0   
3                          5                     6              17169,0   
4                          2                     8                  NaN   
...                      ...                   ...                  ...   
1609                       3                     7              10325,0   
1610                       0                     8               4447,0   
1611                       0                     7                  NaN   
1612                       0                     7                  NaN   
1613                       0                     7              10845,0   

     DateBirth       Salary                       RoleDepartament  \
0         1972  1000000000$                                   NaN   
1         1971  1000000000$                                   NaN   
2         1981  1000000000$   ManaGER  -  Research & Development    
3         1976  1000000000$                                   NaN   
4         1977  1000000000$                                   NaN   
...        ...          ...                                   ...   
1609      1987  1000000000$                                   NaN   
1610      1978  1000000000$                                   NaN

In [57]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'employeecount',
       'employeenumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NUMCOMPANIESWORKED',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TOTALWORKINGYEARS', 'TrainingTimesLastYear', 'WORKLIFEBALANCE',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YEARSWITHCURRMANAGER', 'SameAsMonthlyIncome', 'DateBirth', 'Salary',
       'RoleDepartament', 'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

In [58]:
#en esta rama trabajaremos con las siguientes columnas, todas ellas relacionadas con encuestas de satisfacción realizadas tanto a los empleados como a los encargados
surveys = data.loc [:, ['EnvironmentSatisfaction', 'JobSatisfaction', 'RelationshipSatisfaction', 'WORKLIFEBALANCE', 'JobInvolvement', 'PerformanceRating' ]]
surveys 

EnvironmentSatisfaction  JobSatisfaction  RelationshipSatisfaction  \
0                           1                3                         3   
1                           3                3                         1   
2                           3                4                         4   
3                           1                3                         2   
4                           1                1                         4   
...                       ...              ...                       ...   
1609                        3                4                         1   
1610                        3                2                         2   
1611                       13                3                         4   
1612                        1                4                         4   
1613                        4                3                         2   

     WORKLIFEBALANCE  JobInvolvement PerformanceRating  
0                3,0               3               3,0  
1                3,0               2               3,0  
2                NaN               3               3,0  
3                NaN               3               3,0  
4                3,0               4               3,0  
...              ...             ...               ...  
1609             3,0               2               NaN  
1610             2,0               3               3,0  
1611             3,0               4               3,0  
1612             3,0               3               NaN  
1613             3,0               3               3,0  

[1614 rows x 6 columns]

In [59]:
surveys.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1614 entries, 0 to 1613
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   EnvironmentSatisfaction   1614 non-null   int64 
 1   JobSatisfaction           1614 non-null   int64 
 2   RelationshipSatisfaction  1614 non-null   int64 
 3   WORKLIFEBALANCE           1506 non-null   object
 4   JobInvolvement            1614 non-null   int64 
 5   PerformanceRating         1419 non-null   object
dtypes: int64(4), object(2)
memory usage: 88.3+ KB


## 'employeenumber'

In [60]:
#como es una columna primary key en común con otras tablas, lo haremos de acuerdo con el resto de compañeras

## 'EnvironmentSatisfaction'
Nivel de satisfacción del empleado en relación con su entorno de trabajo. Con valores que estan comprendidos entre el 1 y el 4, siendo el 4 el nivel de máxima satisfacción.

In [61]:
surveys ['EnvironmentSatisfaction'].describe().T
#variable numérica

count    1614.000000
mean        4.294919
std         6.993559
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        49.000000
Name: EnvironmentSatisfaction, dtype: float64

In [62]:
surveys ['EnvironmentSatisfaction'].isnull().sum()
#no hay nulos

0

In [63]:
surveys['EnvironmentSatisfaction'].unique()
# los valores están descritos del 1 al 50, no del 1 al 4. Probablemente sea porque lo han querido hacer como decimal pero no le han puesto el . 
# no podemos sacar conclusiones con los datos de esta manera

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [64]:
#vamos a transformar estos datos de satisfacción a una escala del 1 al 4 para unificar con el resto de columnas. Para ello hacemos un bucle for. 
environment_satisfaction = [1, 3, 4, 2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
                13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
                17, 20, 26, 43]

nueva_satisfaccion = []

for valor in environment_satisfaction:
    nueva_valor = ((valor - 1) * 4) // 49 + 1
    nueva_satisfaccion.append(nueva_valor)

print (nueva_satisfaccion)

[1, 1, 1, 1, 4, 3, 3, 2, 3, 3, 4, 2, 2, 2, 3, 2, 1, 1, 3, 4, 3, 3, 2, 4, 2, 2, 4, 4, 1, 4, 2, 1, 4, 4, 2, 2, 3, 4]


Vamos a categorizar la columna `EnvironmentSatisfaction` para conseguir las siguientes categorías:


- 1 (insatisfecho): puntuación del 1 al 13

- 2 (poco satisfecho): puntuación del 14 al 25

- 3 (satisfecho): puntuación del 26 al 37

- 4 (muy satisfecho): puntuación del 38 al 49

In [65]:
# lo primero que vamos a hacer es crear una función que reciba un número y nos devuelva a qué categoría pertenece

def categorizar_environment(numero):
    
    if numero == 1:
        return 1
    
    elif numero == 2:
        return 2
    
    elif numero == 3:
        return 3
    
    elif numero == 4:
        return 4
    
    elif numero >= 5 and numero <= 14:
        return 1
    
    elif numero >= 15 and numero <= 25:
        return 2

    elif numero >= 26 and numero <= 35:
        return 3
    
    else:
        return 4
    

In [66]:
#llamamos a la función creada
surveys['EnvironmentSatisfaction'] = surveys['EnvironmentSatisfaction'].apply(categorizar_environment)

In [67]:
surveys['EnvironmentSatisfaction'].unique()
#ya tenemos nuestra columna con valores intuitivos y normalizados que podemos utilizar

array([1, 3, 4, 2])

## 'JobSatisfaction'
Nivel de satisfacción del empleado con su trabajo.

In [68]:
surveys ['JobSatisfaction'].describe().T
#variable numérica

count    1614.000000
mean        2.738538
std         1.106163
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: JobSatisfaction, dtype: float64

In [69]:
surveys ['JobSatisfaction'].isnull().sum()
#no tenemos valores nulos 

0

In [70]:
surveys['JobSatisfaction'].unique()
#en este caso los valores están correctos, ya que están clasificados del 1 al 4

array([3, 4, 1, 2])

## 'RelationshipSatisfaction'
Nivel de satisfacción en las relaciones interpersonales del empleado.

In [71]:
surveys['RelationshipSatisfaction'].unique()
#en este caso los valores están correctos, ya que están clasificados del 1 al 4 y son de tipo numérico

array([3, 1, 4, 2])

In [72]:
surveys ['RelationshipSatisfaction'].describe().T
#variable numérica 

count    1614.000000
mean        2.704461
std         1.079031
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: RelationshipSatisfaction, dtype: float64

In [73]:
surveys ['RelationshipSatisfaction'].isnull().sum()

0

## 'WORKLIFEBALANCE'
Equilibrio entre trabajo y vida personal del empleado.

In [74]:
surveys['WORKLIFEBALANCE'].describe().T
#variable categórica

count     1506
unique       4
top        3,0
freq       913
Name: WORKLIFEBALANCE, dtype: object

In [75]:
surveys['WORKLIFEBALANCE'].unique()
# hay que unificar con las demás

array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

In [76]:
surveys['WORKLIFEBALANCE'].isnull().sum()
#108 nulas

108

In [77]:
# Limpiamos los datos: reemplazamos comas y convertir NaN a None
surveys['WORKLIFEBALANCE'] = surveys['WORKLIFEBALANCE'].str.replace(',', '.').astype(float).fillna(np.nan)

# Convertir la columna a entero
surveys['WORKLIFEBALANCE'] = surveys['WORKLIFEBALANCE'].astype('Int64')

In [78]:
surveys['WORKLIFEBALANCE'].isna().sum()/surveys['WORKLIFEBALANCE'].shape[0]*100
#tenemos un 7% de nulos en nuestro dataframe que tendremos que gestionar 

6.691449814126393

In [79]:
surveys['WORKLIFEBALANCE'].unique()

<IntegerArray>
[3, <NA>, 2, 4, 1]
Length: 5, dtype: Int64

## 'JobInvolvement'
Nivel de implicación del empleado en su trabajo.

In [80]:
surveys['JobInvolvement'].describe().T
#variable numérica

count    1614.000000
mean        2.739777
std         0.711567
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         4.000000
Name: JobInvolvement, dtype: float64

In [81]:
surveys['JobInvolvement'].unique()
# correctos: del 1 al 4 

array([3, 2, 4, 1])

In [82]:
surveys['JobInvolvement'].isnull().sum()
#no tenemos nulos

0

## 'PerformanceRating'
Calificación de rendimiento del empleado.

In [83]:
surveys['PerformanceRating'].describe().T
#variable categórica

count     1419
unique       2
top        3,0
freq      1205
Name: PerformanceRating, dtype: object

In [84]:
surveys['PerformanceRating'].unique()
#sólo tenemos valores 3 y 4

array(['3,0', '4,0', nan], dtype=object)

In [85]:
# Limpiamos los datos: reemplazamos comas y convertir NaN a None
surveys['PerformanceRating'] = surveys['PerformanceRating'].str.replace(',', '.').astype(float).fillna(np.nan)

# Convertir la columna a entero
surveys['PerformanceRating'] = surveys['PerformanceRating'].astype('Int64')

In [86]:
surveys['PerformanceRating'].isnull().sum()
#tenemos 195 nulos 

195

In [87]:
surveys['PerformanceRating'].isna().sum()/surveys['PerformanceRating'].shape[0]*100
#tenemos un 12% de nulos

12.0817843866171

In [88]:
surveys['PerformanceRating'].unique()

<IntegerArray>
[3, 4, <NA>]
Length: 3, dtype: Int64

In [89]:
surveys

EnvironmentSatisfaction  JobSatisfaction  RelationshipSatisfaction  \
0                           1                3                         3   
1                           3                3                         1   
2                           3                4                         4   
3                           1                3                         2   
4                           1                1                         4   
...                       ...              ...                       ...   
1609                        3                4                         1   
1610                        3                2                         2   
1611                        1                3                         4   
1612                        1                4                         4   
1613                        4                3                         2   

      WORKLIFEBALANCE  JobInvolvement  PerformanceRating  
0                   3               3                  3  
1                   3               2                  3  
2                <NA>               3                  3  
3                <NA>               3                  3  
4                   3               4                  3  
...               ...             ...                ...  
1609                3               2               <NA>  
1610                2               3                  3  
1611                3               4                  3  
1612                3               3               <NA>  
1613                3               3                  3  

[1614 rows x 6 columns]

In [90]:
surveys.to_csv ('../../files/surveys.csv')

In [91]:
surveys.isnull().sum()

EnvironmentSatisfaction       0
JobSatisfaction               0
RelationshipSatisfaction      0
WORKLIFEBALANCE             108
JobInvolvement                0
PerformanceRating           195
dtype: int64